DMS-1194 Change spec to include Flu and HPV
NHSDigital/immunisation-history-api pull request #184
Opened 2023-05-22 13:32 UTC by nathanwall

## Summary
* Routine Change

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [x] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-05-31 09:01 UTC, ProductBrett commented
@nathanwall I'm not setup to review, I think we want the review by the Tech Author and not Product Owner

2023-06-02 11:34 UTC, ProductBrett approved these changes
Approved as Product Owner having previously reviewed with technical author

2023-06-12 11:11 UTC, ProductBrett approved these changes

2023-06-28 15:48 UTC, ProductBrett requested changes

2023-06-28 15:48 UTC, ProductBrett commented on specification/immunisation-history.yaml
> +    The patient demographic details might differ from those held in the Personal Demographics Service (PDS). To get demographic details from PDS, use the Personal Demographics Service FHIR API.
@nathanwall please update` Personal Demographics Service FHIR API` to
`[Personal Demographics FHIR API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir)`

2023-06-28 15:48 UTC, ProductBrett commented on specification/immunisation-history.yaml
> +    The `FLU` data store is not yet populate and is planned to contain vaccination events captured through a point of care system in England for the last year. It has been approved to be used for cli
@nathanwall please update `populate` to `populated`

2023-06-28 15:48 UTC, ProductBrett commented on specification/immunisation-history.yaml
> +    The `HPV` data store is not yet populated and is planned to be limited at first  to vaccinations captured by the NHAIS system and in England only. It has been approved for use in clinical use cas
Please replace '  ' with ' ' after the word `first`

2023-07-12 13:14 UTC, nigelg approved these changes

2023-07-12 13:16 UTC, nigelg commented
/azp run

2023-07-13 08:15 UTC, merged